name: Deploy GithubPages

on:
  push:
    tags:
      - '*'


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Prepare and deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm install
        npm run deploy -- --no-silent  --name $GITHUB_ACTOR --email $GITHUB_ACTOR@users.noreply.github.com
